version: '3.8'

services:
  app:
    environment:
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
  tasks:
    build: ./tasks_service
    ports:
      - "3000:3000" # Exposing port 3000 for NestJS."
    environment:
      DATABASE_URL: sqlite:////data/tasks.db
    volumes:
      - tasks-data:/data

  # reminders:
  #   build: ./reminders-service
  #   ports:
  #     - "3001:3000" # Exposing port 3001 for NestJS."
  #   environment:
  #     DATABASE_URL: sqlite:////data/reminders.db
  #   volumes:
  #     - reminders-data:/data

volumes:
  tasks-data:
  reminders-data:
